### ISSUE TITLE
My Profile window always asks about unsaved changes

### ISSUE THREAD

**Issue by cseppan** [USEPA-OAQPS/emf#60] opened 2021-07-23 04:40 UTC
Steps to reproduce:

From the Manage menu, select My Profile
Without doing anything, click the Close button at the bottom of the window
The "Discard changes?" prompt is displayed even though no changes have been made

Note that clicking the window close button (upper right hand corner) doesn't bring up the prompt

**Comment by ddelvecchio** [comment] 2021-08-08 02:21
I'm not able to reproduce this issue, were you seeing this on your Mac or Windows?

I'll focused through all the fields and still didn't get a prompt when closing the window?

**Comment by cseppan** [comment] 2021-08-08 02:29
Just checked on Windows - the problem happens only when using a non-admin account

**Comment by ddelvecchio** [comment] 2021-08-08 02:40
I logged in using "qha" account on production, he is not an admin and I'm still not seeing the issue.

**Comment by cseppan** [comment] 2021-08-08 02:57
It looks like it's related to using the "Hide Feature" option, not admin/non-admin (the accessibility test user will be both a non-admin and have several features hidden). I logged in with my usual admin account and added a feature to hide then saved the changes and closed the window. All good so far. Now when I open the My Profile window, I see a feature listed in the Hide Feature box and the window is marked as dirty immediately (asterisk in the title bar, hitting Close brings up the confirm dialog).

**Closed** 2021-08-09 02:45 UTC
Labels: accessibility test plan
